[[main]]
  name = "Releases"
  pageRef = "/releases"
  weight = 10

[[main]]
  name = "Docs"
  pageRef = "/docs"
  weight = 20
  
[[main]]
  name = "Blog"
  pageRef = "/blog"
  weight = 30

[[main]]
  identifier = "github"
  pre = "github"
  url = "/repositories"
  weight = 40

[[footer]]
  name = "Elliott"
  url = "https://elliottfournierrobert.ca"
  weight = 10

[[footer]]
  name = "Arianne"
  url = "https://arianne.dev"
  weight = 20